repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
        pass_filenames: true
        args: ['src',]
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        pass_filenames: true
        args: ['src',]
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        pass_filenames: true
        args: ['src',]
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
        pass_filenames: false
        args: ['src',]
